package com.fish_dan_.data_energistics.api.production;

import appeng.api.stacks.AEFluidKey;
import appeng.api.stacks.AEItemKey;
import appeng.api.stacks.AEKey;
import appeng.api.stacks.GenericStack;

import net.minecraft.core.HolderLookup;
import net.minecraft.nbt.ListTag;
import net.minecraft.world.item.ItemStack;

import it.unimi.dsi.fastutil.objects.Object2LongLinkedOpenHashMap;
import it.unimi.dsi.fastutil.objects.Object2LongMap;
import it.unimi.dsi.fastutil.objects.Object2LongMaps;

/** Immutable, ordered AE resource amounts generated by one production batch. */
public record DataProductionOutput(Object2LongMap<AEKey> amounts) {

    private static final DataProductionOutput EMPTY = new DataProductionOutput(Object2LongMaps.emptyMap());

    public DataProductionOutput {
        Object2LongLinkedOpenHashMap<AEKey> copy = new Object2LongLinkedOpenHashMap<>(amounts.size());
        for (Object2LongMap.Entry<AEKey> entry : amounts.object2LongEntrySet()) {
            requirePositive(entry.getKey(), entry.getLongValue());
            copy.put(entry.getKey(), entry.getLongValue());
        }
        amounts = Object2LongMaps.unmodifiable(copy);
    }

    public static DataProductionOutput empty() {
        return EMPTY;
    }

    public static Accumulator accumulator() {
        return new Accumulator();
    }

    public static DataProductionOutput fromStacks(Iterable<ItemStack> stacks) {
        return accumulator().addStacks(stacks).build();
    }

    public boolean isEmpty() {
        return amounts.isEmpty();
    }

    public long amount(AEKey key) {
        return amounts.getLong(key);
    }

    public DataProductionOutput add(AEKey key, long amount) {
        return accumulator().add(this).add(key, amount).build();
    }

    public DataProductionOutput merge(DataProductionOutput other) {
        if (other.isEmpty()) {
            return this;
        }
        if (isEmpty()) {
            return other;
        }
        return accumulator().add(this).add(other).build();
    }

    public DataProductionOutput repeat(int repetitions) {
        return accumulator().addRepeated(this, repetitions).build();
    }

    public Object2LongMap<AEItemKey> itemAmounts() {
        Object2LongLinkedOpenHashMap<AEItemKey> items = new Object2LongLinkedOpenHashMap<>();
        for (Object2LongMap.Entry<AEKey> entry : amounts.object2LongEntrySet()) {
            if (entry.getKey() instanceof AEItemKey item) {
                items.put(item, entry.getLongValue());
            }
        }
        return Object2LongMaps.unmodifiable(items);
    }

    public Object2LongMap<AEFluidKey> fluidAmounts() {
        Object2LongLinkedOpenHashMap<AEFluidKey> fluids = new Object2LongLinkedOpenHashMap<>();
        for (Object2LongMap.Entry<AEKey> entry : amounts.object2LongEntrySet()) {
            if (entry.getKey() instanceof AEFluidKey fluid) {
                fluids.put(fluid, entry.getLongValue());
            }
        }
        return Object2LongMaps.unmodifiable(fluids);
    }

    public long itemAmount() {
        long result = 0;
        for (Object2LongMap.Entry<AEKey> entry : amounts.object2LongEntrySet()) {
            if (entry.getKey() instanceof AEItemKey) {
                result = Math.addExact(result, entry.getLongValue());
            }
        }
        return result;
    }

    public ListTag writeToNbt(HolderLookup.Provider registries) {
        ListTag entries = new ListTag();
        for (Object2LongMap.Entry<AEKey> entry : amounts.object2LongEntrySet()) {
            entries.add(GenericStack.writeTag(registries, new GenericStack(entry.getKey(), entry.getLongValue())));
        }
        return entries;
    }

    public static DataProductionOutput readFromNbt(HolderLookup.Provider registries, ListTag entries) {
        Accumulator restored = accumulator();
        for (int index = 0; index < entries.size(); index++) {
            GenericStack stack = GenericStack.readTag(registries, entries.getCompound(index));
            if (stack == null) {
                throw new IllegalArgumentException("Invalid data-production output entry at index " + index);
            }
            restored.add(stack.what(), stack.amount());
        }
        return restored.build();
    }

    private static void requirePositive(AEKey key, long amount) {
        if (key == null || amount <= 0) {
            throw new IllegalArgumentException("Data-production output requires a key and a positive amount");
        }
    }

    public static final class Accumulator {

        private final Object2LongLinkedOpenHashMap<AEKey> amounts = new Object2LongLinkedOpenHashMap<>();

        public Accumulator add(AEKey key, long amount) {
            requirePositive(key, amount);
            this.amounts.mergeLong(key, amount, Math::addExact);
            return this;
        }

        public Accumulator add(DataProductionOutput output) {
            return addRepeated(output, 1);
        }

        public Accumulator addRepeated(DataProductionOutput output, int repetitions) {
            if (repetitions < 0) {
                throw new IllegalArgumentException("repetitions cannot be negative");
            }
            if (repetitions > 0) {
                for (Object2LongMap.Entry<AEKey> entry : output.amounts.object2LongEntrySet()) {
                    add(entry.getKey(), Math.multiplyExact(entry.getLongValue(), repetitions));
                }
            }
            return this;
        }

        public Accumulator addStacks(Iterable<ItemStack> stacks) {
            return addRepeatedStacks(stacks, 1);
        }

        public Accumulator addRepeatedStacks(Iterable<ItemStack> stacks, int repetitions) {
            if (repetitions < 0) {
                throw new IllegalArgumentException("repetitions cannot be negative");
            }
            if (repetitions > 0) {
                for (ItemStack stack : stacks) {
                    if (!stack.isEmpty()) {
                        AEItemKey key = AEItemKey.of(stack);
                        if (key == null) {
                            throw new IllegalArgumentException("Non-empty generated stack has no AE item key");
                        }
                        add(key, Math.multiplyExact((long) stack.getCount(), repetitions));
                    }
                }
            }
            return this;
        }

        public DataProductionOutput build() {
            return this.amounts.isEmpty() ? empty() : new DataProductionOutput(this.amounts);
        }
    }
}
